<?php

namespace pi\FrontEnd\FicheDeDressageBundle\Repository;

/**
 * f_dressageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class f_dressageRepository extends \Doctrine\ORM\EntityRepository
{
}
