<?php

namespace pi\FrontEnd\AnimaleBundle\Repository;

/**
 * sosDisparitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sosDisparitionRepository extends \Doctrine\ORM\EntityRepository
{
}
