<?php

namespace pi\FrontEnd\AdoptionBundle\Repository;

/**
 * AdoptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdoptionRepository extends \Doctrine\ORM\EntityRepository
{
}
