<?php

namespace pi\FrontEnd\PetiteurBundle\Repository;

/**
 * DemandeGardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeGardRepository extends \Doctrine\ORM\EntityRepository
{
}
