<?php

namespace pi\FrontEnd\PetiteurBundle\Repository;

/**
 * PetiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetiteurRepository extends \Doctrine\ORM\EntityRepository
{
}
