<?php

namespace pi\FrontEnd\PetiteurBundle\Repository;

/**
 * PetiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetiteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteAdmin($Offrepetiteur){

        $qb = $this->createQueryBuilder('Offrepetiteur');
        $query = $qb->delete('PetiteurBundle:OffrePetiteur', 'Offrepetiteur')
            ->where('Offrepetiteur.id = :Id')
            ->setParameter('Id', $Offrepetiteur->getId())
            ->getQuery();

        $query->execute();
    }
}
