<?php

namespace pi\FrontEnd\CouncoursBundle\Repository;

/**
 * concourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class concourRepository extends \Doctrine\ORM\EntityRepository
{
}
