<?php

namespace pi\FrontEnd\CouncoursBundle\Repository;

/**
 * concoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class concoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function accepterRepository($id)
    {
        $query = $this->getEntityManager()->createQuery("select m from pi\FrontEnd\CouncoursBundle\Entity\participation where m.id = :x" )->setParameter('x',$id);
        return $query->getResult();

    }
}
