<?php

namespace pi\FrontEnd\CouncoursBundle\Repository;

/**
 * demandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demandesRepository extends \Doctrine\ORM\EntityRepository
{
}
