<?php

namespace pi\FrontEnd\FicheDeSoinBundle\Repository;

/**
 * animalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class animalRepository extends \Doctrine\ORM\EntityRepository
{
}
