<?php

namespace pi\FrontEnd\FicheDeSoinBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * animalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
        class animalRepository extends EntityRepository
        {

        }
