<?php

namespace pi\FrontEnd\FicheDeSoinBundle\Repository;

/**
 * f_soinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class f_soinRepository extends \Doctrine\ORM\EntityRepository
{
}
