<?php

namespace pi\FrontEnd\FicheDeSoinBundle\Repository;
use pi\FrontEnd\FicheDeSoinBundle\Entity\feedback;


/**
 * feedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class feedbackRepository extends \Doctrine\ORM\EntityRepository
{
    public function add($id)
    {

        return $this->createQueryBuilder('f')
            ->update('FicheDeSoinBundle:feedback','f')
            ->set('f.likeNumber', 'f.likeNumber + 1')
            ->where('f.idanimal = ?1')
            ->setParameter(1,$id)
            ->getQuery()
            ->execute();
    }



//    public function add($id){
//        $query=$this->getEntityManager()
//            ->createQuery('UPDATE FicheDeSoinBundle:feedback f set f.like_number=10 WHERE f.id_animal = 5')
//            ->setParameter('idd',$id);
//        return $query->execute();
//    }

}
