<?php

namespace pi\FrontEnd\FicheDeSoinBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function  findVeterinaireQB(){
        $queryBuilder=$this
            ->createQueryBuilder('s');
        $queryBuilder
            ->where("s.roles=:roles")
            ->andWhere("s.confirmation=:val")
            ->setParameter('roles','a:1:{i:0;s:9:"ROLE_VETE";}')
            ->setParameter('val','1');
        return $queryBuilder->getQuery()->getResult();
    }

    public function  findUser(){
        $queryBuilder=$this
            ->createQueryBuilder('s');
        $queryBuilder
            ->where("s.roles=:roles")
            ->orWhere("s.roles=:roledres")
            ->setParameter('roles','a:1:{i:0;s:9:"ROLE_VETE";}')
            ->setParameter('roledres','a:1:{i:0;s:10:"ROLE_DRESS";}');

        return $queryBuilder->getQuery()->getResult();

    }

}
