<?php

namespace pi\FrontEnd\CommercialBundle\Repository;

/**
 * NourritureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NourritureRepository extends \Doctrine\ORM\EntityRepository
{
}
